/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAOS.DAOAeroporto;
import DAOS.DAOCompanhia_A;
import DAOS.DAOVoo;
import JBIN.Aeroporto;
import JBIN.*;
import TMS.TableModelVoo;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Lucas
 */
public class VooCRUD extends javax.swing.JFrame {

    TableModelVoo tableModelVoo;
    DAOVoo daoVoo = new DAOVoo();
    DAOAeroporto daoAeroporto = new DAOAeroporto();
    DAOCompanhia_A daoCompanhiaA = new DAOCompanhia_A();

    /**
     * Creates new form VooCRUD
     */
    public VooCRUD() {
        initComponents();
        this.tableModelVoo = new TableModelVoo();
        this.jTable1.setModel(tableModelVoo);

        List<Voo> voos = daoVoo.lista();
        for (Voo voo : voos) {
            this.tableModelVoo.add(voo);
        }

        List<Aeroporto> ars = daoAeroporto.lista();
        for (Aeroporto ar : ars) {
            comboOrigem.addItem(ar.getCidade());
            comboDestino.addItem(ar.getCidade());
        }

        List<Companhia_A> cas = daoCompanhiaA.lista();
        for (Companhia_A ca : cas) {
            comboComp.addItem(ca.getNome());
        }

        comboComp.setSelectedIndex(0);
        comboOrigem.setSelectedIndex(0);
        comboDestino.setSelectedIndex(0);

        comboEst.addItem("Planejado");
        comboEst.addItem("Executado");
        comboEst.setSelectedIndex(0);

        MaskFormatter mascaraData = null;
        LocalDate datas = LocalDate.now();

        try {

            mascaraData = new MaskFormatter("##/##/####");
            mascaraData.setPlaceholderCharacter('_');
        } catch (ParseException excp) {
            System.err.println("Erro na formatação: " + excp.getMessage());
            System.exit(-1);
        }

        this.data.setFormatterFactory(new DefaultFormatterFactory(mascaraData));
        data.setBounds(150, 160, 100, 20);

        this.data.setText(String.valueOf(datas.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        comboOrigem = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboDestino = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        data = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        duracao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cap = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        aviao = new javax.swing.JTextField();
        comboEst = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        limpa = new javax.swing.JButton();
        altera = new javax.swing.JButton();
        exclui = new javax.swing.JButton();
        salva = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        comboComp = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vôo CRUD");

        jLabel1.setText("Código:");

        jLabel2.setText("Origem:");

        jLabel3.setText("Destino:");

        data.setFormatterFactory(null);
        data.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataFocusLost(evt);
            }
        });

        jLabel4.setText("Data:");

        jLabel5.setText("Duração:");

        jLabel6.setText("Companhia Aéria:");

        jLabel7.setText("Capacidade:");

        jLabel8.setText("Avião:");

        comboEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstActionPerformed(evt);
            }
        });

        jLabel9.setText("Estado:");

        limpa.setText("Limpar");
        limpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpaMouseClicked(evt);
            }
        });

        altera.setText("Alterar");

        exclui.setText("Excluir");
        exclui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluiMouseClicked(evt);
            }
        });

        salva.setText("Salvar");
        salva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvaMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(comboEst, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(duracao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(comboComp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cap, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(aviao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(limpa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(81, 81, 81)
                            .addComponent(altera, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(198, 198, 198)
                            .addComponent(exclui, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salva, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aviao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exclui, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(salva, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(altera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataFocusLost

    }//GEN-LAST:event_dataFocusLost

    private void comboEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboEstActionPerformed

    private void salvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvaMouseClicked
        // TODO add your handling code here:
        Voo voo = new Voo();

        String origem = (String) comboOrigem.getSelectedItem();
        String destino = (String) comboDestino.getSelectedItem();
        LocalDate dataF;

        List<Aeroporto> ars = daoAeroporto.lista();
        for (Aeroporto ar : ars) {
            if (origem.equals(ar.getCidade())) {
                voo.setOrigem(ar);
            }

            if (destino.equals(ar.getCidade())) {
                voo.setDestino(ar);
            }
        }

        LocalDate dataf = LocalDate.now();
        DateTimeFormatter df = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        dataf = LocalDate.parse(data.getText(), df);

        voo.setData(dataf);
        voo.setDuracao(Integer.parseInt(duracao.getText()));

        String compA = (String) comboComp.getSelectedItem();
        List<Companhia_A> cas = daoCompanhiaA.lista();
        for (Companhia_A ca : cas) {
            if (compA.equals(ca.getNome())) {
                voo.setCompanhia(ca);
            }
        }

        voo.setCapacidade(Long.parseLong(cap.getText()));
        voo.setAviao(aviao.getText());
        voo.setEstado((String) comboEst.getSelectedItem());
        int id = daoVoo.adiciona(voo);

        List<Voo> voos = daoVoo.lista();
        for (Voo voof : voos) {
            if (id == voof.getId()) {
                this.tableModelVoo.add(voof);
            }
        }

    }//GEN-LAST:event_salvaMouseClicked

    private void limpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpaMouseClicked
        // TODO add your handling code here:
        aviao.setText("");
        cod.setText("");
        cap.setText("");
        duracao.setText("");
    }//GEN-LAST:event_limpaMouseClicked

    private void excluiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluiMouseClicked
        // TODO add your handling code here:
        Voo voo = new Voo();
        voo.setId(Long.parseLong(cod.getText()));
        daoVoo.exclui(voo);
        for (int i = 0; i < tableModelVoo.getRowCount(); i++) {
            if (tableModelVoo.get(i).getId() == voo.getId()) {
                tableModelVoo.remove(i);
            }
        }
    }//GEN-LAST:event_excluiMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int linha = this.jTable1.getSelectedRow();
        Voo voo = this.tableModelVoo.get(linha);
        this.cod.setText(String.valueOf(voo.getId()));
        List<Aeroporto> ars = daoAeroporto.lista();
        for (Aeroporto ar : ars) {
            if (voo.getOrigem().getNome().equals(ar.getNome())) {
                comboOrigem.setSelectedItem(ar.getCidade());
            }

            if (voo.getDestino().getNome().equals(ar.getNome())) {
                comboDestino.setSelectedItem(ar.getCidade());
            }
        }

        this.data.setText(String.valueOf(voo.getData().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))));
        this.duracao.setText(String.valueOf(voo.getDuracao()));

        List<Companhia_A> cas = daoCompanhiaA.lista();
        for (Companhia_A ca : cas) {
            if (voo.getCompanhia().getNome().equals(ca.getNome())) {
                comboComp.setSelectedItem(ca.getNome());
            }
        }

        this.cap.setText(String.valueOf(voo.getCapacidade()));
        this.aviao.setText(voo.getAviao());
        this.comboEst.setSelectedItem(voo.getEstado());

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VooCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VooCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VooCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VooCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VooCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altera;
    private javax.swing.JTextField aviao;
    private javax.swing.JTextField cap;
    private javax.swing.JTextField cod;
    private javax.swing.JComboBox<String> comboComp;
    private javax.swing.JComboBox<String> comboDestino;
    private javax.swing.JComboBox<String> comboEst;
    private javax.swing.JComboBox<String> comboOrigem;
    private javax.swing.JFormattedTextField data;
    private javax.swing.JTextField duracao;
    private javax.swing.JButton exclui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton limpa;
    private javax.swing.JButton salva;
    // End of variables declaration//GEN-END:variables
}
